apiVersion: v1
kind: Service
metadata:
  name: laravel
  namespace: laravel-ns
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
